
// category
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const CREATE_CATEGORY_REDUCER = "CREATE_CATEGORY_REDUCER"
export const GET_CATEGORY = "GET_CATEGORY"
export const GET_CATEGORY_REDUCER = "GET_CATEGORY_REDUCER"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const UPDATE_CATEGORY_REDUCER = "UPDATE_CATEGORY_REDUCER"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const DELETE_CATEGORY_REDUCER = "DELETE_CATEGORY_REDUCER"

// subcategory

export const CREATE_SUBCATEGORY_REDUCER = "CREATE_SUBCATEGORY_REDUCER"
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
export const GET_SUBCATEGORY = "GET_SUBCATEGORY"
export const GET_SUBCATEGORY_REDUCER = "GET_SUBCATEGORY_REDUCER"
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY"
export const UPDATE_SUBCATEGORY_REDUCER = "UPDATE_SUBCATEGORY_REDUCER"
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"
export const DELETE_SUBCATEGORY_REDUCER = "DELETE_SUBCATEGORY_REDUCER"

//brands 

export const CREATE_BRAND_REDUCER = "CREATE_BRAND_REDUCER"
export const CREATE_BRAND = "CREATE_BRAND"
export const GET_BRAND = "GET_BRAND"
export const GET_BRAND_REDUCER = "GET_BRAND_REDUCER"
export const UPDATE_BRAND = "UPDATE_BRAND"
export const UPDATE_BRAND_REDUCER = "UPDATE_BRAND_REDUCER"
export const DELETE_BRAND = "DELETE_BRAND"
export const DELETE_BRAND_REDUCER = "DELETE_BRAND_REDUCER"

//features 

export const CREATE_FEATURE_REDUCER = "CREATE_FEATURE_REDUCER"
export const CREATE_FEATURE = "CREATE_FEATURE"
export const GET_FEATURE = "GET_FEATURE"
export const GET_FEATURE_REDUCER = "GET_FEATURE_REDUCER"
export const UPDATE_FEATURE = "UPDATE_FEATURE"
export const UPDATE_FEATURE_REDUCER = "UPDATE_FEATURE_REDUCER"
export const DELETE_FEATURE = "DELETE_FEATURE"
export const DELETE_FEATURE_REDUCER = "DELETE_FEATURE_REDUCER"

//PRODUCTs 

export const CREATE_PRODUCT_REDUCER = "CREATE_PRODUCT_REDUCER"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_REDUCER = "GET_PRODUCT_REDUCER"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_REDUCER = "UPDATE_PRODUCT_REDUCER"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_REDUCER = "DELETE_PRODUCT_REDUCER"

//FAQs 

export const CREATE_FAQ_REDUCER = "CREATE_FAQ_REDUCER"
export const CREATE_FAQ = "CREATE_FAQ"
export const GET_FAQ = "GET_FAQ"
export const GET_FAQ_REDUCER = "GET_FAQ_REDUCER"
export const UPDATE_FAQ = "UPDATE_FAQ"
export const UPDATE_FAQ_REDUCER = "UPDATE_FAQ_REDUCER"
export const DELETE_FAQ = "DELETE_FAQ"
export const DELETE_FAQ_REDUCER = "DELETE_FAQ_REDUCER"

//SETTINGs 

export const CREATE_SETTING_REDUCER = "CREATE_SETTING_REDUCER"
export const CREATE_SETTING = "CREATE_SETTING"
export const GET_SETTING = "GET_SETTING"
export const GET_SETTING_REDUCER = "GET_SETTING_REDUCER"
export const UPDATE_SETTING = "UPDATE_SETTING"
export const UPDATE_SETTING_REDUCER = "UPDATE_SETTING_REDUCER"


//TESTIMONIAL

export const CREATE_TESTIMONIAL_REDUCER = "CREATE_TESTIMONIAL_REDUCER"
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL"
export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_REDUCER = "GET_TESTIMONIAL_REDUCER"
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_REDUCER = "UPDATE_TESTIMONIAL_REDUCER"
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_REDUCER = "DELETE_TESTIMONIAL_REDUCER"


//CART

export const CREATE_CART_REDUCER = "CREATE_CART_REDUCER"
export const CREATE_CART = "CREATE_CART"
export const GET_CART = "GET_CART"
export const GET_CART_REDUCER = "GET_CART_REDUCER"
export const UPDATE_CART = "UPDATE_CART"
export const UPDATE_CART_REDUCER = "UPDATE_CART_REDUCER"
export const DELETE_CART = "DELETE_CART"
export const DELETE_CART_REDUCER = "DELETE_CART_REDUCER"

//WISHLIST

export const CREATE_WISHLIST_REDUCER = "CREATE_WISHLIST_REDUCER"
export const CREATE_WISHLIST = "CREATE_WISHLIST"
export const GET_WISHLIST = "GET_WISHLIST"
export const GET_WISHLIST_REDUCER = "GET_WISHLIST_REDUCER"
export const UPDATE_WISHLIST = "UPDATE_WISHLIST"
export const UPDATE_WISHLIST_REDUCER = "UPDATE_WISHLIST_REDUCER"
export const DELETE_WISHLIST = "DELETE_WISHLIST"
export const DELETE_WISHLIST_REDUCER = "DELETE_WISHLIST_REDUCER"

//NEWSLETTER

export const CREATE_NEWSLETTER_REDUCER = "CREATE_NEWSLETTER_REDUCER"
export const CREATE_NEWSLETTER = "CREATE_NEWSLETTER"
export const GET_NEWSLETTER = "GET_NEWSLETTER"
export const GET_NEWSLETTER_REDUCER = "GET_NEWSLETTER_REDUCER"
export const UPDATE_NEWSLETTER = "UPDATE_NEWSLETTER"
export const UPDATE_NEWSLETTER_REDUCER = "UPDATE_NEWSLETTER_REDUCER"
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER"
export const DELETE_NEWSLETTER_REDUCER = "DELETE_NEWSLETTER_REDUCER"

//ADDRESS

export const CREATE_ADDRESS_REDUCER = "CREATE_ADDRESS_REDUCER"
export const CREATE_ADDRESS = "CREATE_ADDRESS"
export const GET_ADDRESS = "GET_ADDRESS"
export const GET_ADDRESS_REDUCER = "GET_ADDRESS_REDUCER"
export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const UPDATE_ADDRESS_REDUCER = "UPDATE_ADDRESS_REDUCER"
export const DELETE_ADDRESS = "DELETE_ADDRESS"
export const DELETE_ADDRESS_REDUCER = "DELETE_ADDRESS_REDUCER"


//ORDER

export const CREATE_ORDER_REDUCER = "CREATE_ORDER_REDUCER"
export const CREATE_ORDER = "CREATE_ORDER"
export const GET_ORDER = "GET_ORDER"
export const GET_ORDER_REDUCER = "GET_ORDER_REDUCER"
export const UPDATE_ORDER = "UPDATE_ORDER"
export const UPDATE_ORDER_REDUCER = "UPDATE_ORDER_REDUCER"
export const DELETE_ORDER = "DELETE_ORDER"
export const DELETE_ORDER_REDUCER = "DELETE_ORDER_REDUCER"

//CONTACTUS

export const CREATE_CONTACTUS_REDUCER = "CREATE_CONTACTUS_REDUCER"
export const CREATE_CONTACTUS = "CREATE_CONTACTUS"
export const GET_CONTACTUS = "GET_CONTACTUS"
export const GET_CONTACTUS_REDUCER = "GET_CONTACTUS_REDUCER"
export const UPDATE_CONTACTUS = "UPDATE_CONTACTUS"
export const UPDATE_CONTACTUS_REDUCER = "UPDATE_CONTACTUS_REDUCER"
export const DELETE_CONTACTUS = "DELETE_CONTACTUS"
export const DELETE_CONTACTUS_REDUCER = "DELETE_CONTACTUS_REDUCER"


//USER

export const CREATE_USER_REDUCER = "CREATE_USER_REDUCER"
export const CREATE_USER = "CREATE_USER"
export const GET_USER = "GET_USER"
export const GET_USER_REDUCER = "GET_USER_REDUCER"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_REDUCER = "UPDATE_USER_REDUCER"
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_REDUCER = "DELETE_USER_REDUCER"